"""Train a multi-output Random Forest from the explicitly synthetic dummy dataset."""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import GroupShuffleSplit

from feature_schema import FEATURE_COLUMNS, FEATURE_DEFINITIONS, FEATURE_UNITS, SCHEMA_VERSION, TARGETS, TARGET_COLUMNS

ROOT = Path(__file__).resolve().parent
MODEL_PATH = ROOT / "models" / "dummy_hpdc_model.joblib"
METADATA_PATH = ROOT / "models" / "dummy_hpdc_model_metadata.json"
REQUIRED_IDS = ["component_id", "trial_id", "data_source", "generation_seed"]


def validate_data(frame: pd.DataFrame) -> pd.DataFrame:
    if frame.empty:
        raise ValueError("Training CSV has no rows.")
    expected = REQUIRED_IDS + FEATURE_COLUMNS + TARGET_COLUMNS
    missing = [column for column in expected if column not in frame.columns]
    if missing:
        raise ValueError("Dataset is missing required columns: " + ", ".join(missing))
    frame = frame[expected].copy()
    if set(frame.data_source.astype(str).str.lower()) != {"synthetic_dummy"}:
        raise ValueError("This trainer accepts only rows labelled data_source=synthetic_dummy.")
    if frame.component_id.isna().any() or frame.trial_id.isna().any() or frame.trial_id.duplicated().any():
        raise ValueError("component_id and trial_id must be present; trial_id must be unique.")
    if frame.component_id.astype(str).str.strip().eq("").any() or frame.trial_id.astype(str).str.strip().eq("").any():
        raise ValueError("component_id and trial_id cannot be blank.")
    frame["generation_seed"] = pd.to_numeric(frame.generation_seed, errors="coerce")
    if frame.generation_seed.isna().any() or not np.isfinite(frame.generation_seed).all() or frame.generation_seed.nunique() != 1 or (frame.generation_seed % 1 != 0).any():
        raise ValueError("Dataset must contain exactly one documented generation_seed.")
    for column in FEATURE_COLUMNS + TARGET_COLUMNS:
        frame[column] = pd.to_numeric(frame[column], errors="coerce")
        if frame[column].isna().any() or not np.isfinite(frame[column]).all():
            raise ValueError(f"{column} contains missing or non-finite values.")
        if (frame[column] <= 0).any():
            raise ValueError(f"{column} must contain positive values.")
    for column in ("solid_count", "face_count", "edge_count", "vertex_count"):
        if not np.equal(frame[column], np.floor(frame[column])).all():
            raise ValueError(f"{column} must contain integer counts.")
    if frame.component_id.nunique() < 10:
        raise ValueError("At least ten distinct components are needed for a grouped holdout.")
    return frame


def train(data_path=ROOT / "data" / "dummy_hpdc_trials.csv", model_path=MODEL_PATH,
          metadata_path=METADATA_PATH):
    data_path = Path(data_path)
    if not data_path.is_file():
        raise FileNotFoundError(f"Training data not found: {data_path}. Run generate_dummy_data.py first.")
    frame = validate_data(pd.read_csv(data_path))
    x, y, groups = frame[FEATURE_COLUMNS], frame[TARGET_COLUMNS], frame.component_id.astype(str)
    splitter = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
    train_idx, test_idx = next(splitter.split(x, y, groups))
    model = RandomForestRegressor(n_estimators=180, min_samples_leaf=2, random_state=42, n_jobs=1)
    model.fit(x.iloc[train_idx], y.iloc[train_idx])
    predicted = model.predict(x.iloc[test_idx])
    baseline = np.tile(y.iloc[train_idx].mean(axis=0).to_numpy(), (len(test_idx), 1))
    metrics = {}
    for index, target in enumerate(TARGET_COLUMNS):
        actual = y.iloc[test_idx, index]
        metrics[target] = {
            "mae": float(mean_absolute_error(actual, predicted[:, index])),
            "rmse": float(np.sqrt(mean_squared_error(actual, predicted[:, index]))),
            "mean_baseline_mae": float(mean_absolute_error(actual, baseline[:, index])),
        }
    metadata = {
        "model_version": "dummy-synthetic-1.0",
        "model_kind": "synthetic_dummy_regression",
        "schema_version": SCHEMA_VERSION,
        "dataset_provenance": "synthetic/dummy data generated by generate_dummy_data.py",
        "synthetic_seed": int(frame.generation_seed.iloc[0]),
        "training_date_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "feature_columns": FEATURE_COLUMNS,
        "feature_units": FEATURE_UNITS,
        "feature_definitions": FEATURE_DEFINITIONS,
        "target_columns": TARGET_COLUMNS,
        "target_units": {target: unit for target, (_, unit, _) in TARGETS.items()},
        "feature_ranges": {column: {"min": float(x.iloc[train_idx][column].min()),
                                    "max": float(x.iloc[train_idx][column].max())} for column in FEATURE_COLUMNS},
        "target_ranges": {column: {"min": float(y.iloc[train_idx][column].min()),
                                    "max": float(y.iloc[train_idx][column].max())} for column in TARGET_COLUMNS},
        "training_rows": int(len(train_idx)),
        "test_rows": int(len(test_idx)),
        "training_components": int(groups.iloc[train_idx].nunique()),
        "test_components": int(groups.iloc[test_idx].nunique()),
        "validation_method": "80/20 GroupShuffleSplit by component_id; random_state=42",
        "metrics": metrics,
        "limitations": "All inputs/targets are artificial formula-based software fixtures. Metrics are only a pipeline check, not HPDC evidence. Not for production, safety, quality, or optimization.",
    }
    model_path, metadata_path = Path(model_path), Path(metadata_path)
    model_path.parent.mkdir(parents=True, exist_ok=True)
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_model = model_path.with_name(model_path.name + ".tmp")
    temporary_meta = metadata_path.with_name(metadata_path.name + ".tmp")
    joblib.dump(model, temporary_model)
    temporary_meta.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    temporary_model.replace(model_path)
    temporary_meta.replace(metadata_path)
    print(json.dumps({"model": str(model_path), "metadata": str(metadata_path),
                      "training_rows": len(train_idx), "test_rows": len(test_idx),
                      "data_source": "synthetic_dummy", "metrics": metrics}, indent=2))
    return model, metadata


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", default=str(ROOT / "data" / "dummy_hpdc_trials.csv"))
    parser.add_argument("--model-out", default=str(MODEL_PATH))
    parser.add_argument("--metadata-out", default=str(METADATA_PATH))
    args = parser.parse_args()
    try:
        train(args.data, args.model_out, args.metadata_out)
    except Exception as exc:
        raise SystemExit(f"Training stopped; no new model was saved: {exc}") from exc


if __name__ == "__main__":
    main()
